version: '3.6'

services:
  amogus:
    build: .
    command: sh -c "npm install && npm start"
    volumes:
      - ./:/app
    networks:
      - AmogusTube
    environment:
      APP_NAME: AmogusTube
      APP_ENV: development
    ports:
      - "3000:3000"

networks:
  AmogusTube:
    name: AmogusTube_Internal