version: '3.6'

services:
  AmogusTube:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    networks:
      - Amogus
    environment:
      APP_NAME: AmogusTube
      APP_ENV: development
    ports:
      - "3000:3000"

networks:
  AmogusTube:
    name: AmogusTube_Internal